# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-26 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200226_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='followers',
        ),
    ]
