# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-26 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200226_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='activated',
            new_name='is_activated',
        ),
    ]
