# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurents', '0003_restaurant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
