# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-22 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='content',
            new_name='contents',
        ),
    ]
