# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-26 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20200222_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='contents',
            field=models.TextField(help_text='Separate each item by comma'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='excludes',
            field=models.TextField(blank=True, help_text='Separate each item by comma', null=True),
        ),
    ]
